### PR TITLE
#20 ignore prefixes for query parameters and cookies

### PR DESCRIPTION
**Pull request by marcrobertscamao**
First implementation to exclude prefixes inline with #20

### CODE REVIEW

**Comment by mficzel** [comment]
@kitsunet i kindoff like the feature to get a readable configuration for a larger cookie zoo. What du you think?

**Review by mficzel — DISMISSED** [review]
I generally like this and can confirm that it works as documented. My brain does not process array_reduce too well but that is probably more my personal issue.

**Comment by mficzel** [comment]
After seeing pr #22 i changed my mind. I think the opt in approach via `respect` is cleaner concept wise.

**Comment by mficzel** [comment]
@marcrobertscamao would #22 solve your usecase aswell? It has a much simpler structure but kindoff turns the whole problem around.

**Comment by marcrobertscamao** [comment]
@mficzel I think #22 should cover our needs, thanks

**Pull request closed without merging**
